version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python_project

permissions:
   - object: /home/ubuntu/python_project
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      runas: root
  AfterInstall:
    - location: scripts/install_python_dependencies.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      runas: root
  

